markdown: kramdown
highlighter: null
permalink: /:title
highlighter: pygments

url:
baseurl:

redcarpet:
  extensions: [strikethrough, tables]

comments: true

sass:
  sass_dir: public/css
  style: :compressed